import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kanal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" classNameName="dark">
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css"
          rel="stylesheet"
        />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
      </head>
      <AuthContextProvider>
        <body classNameName={inter.classNameName}>{children}</body>
      </AuthContextProvider>
    </html>
  );
}
